import React, { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, CheckCircle2, FileCheck2, MessageCircle, Minus, Phone, Plus, Send, ShieldCheck } from 'lucide-react';
import { Header } from './sukukUpdated/components/Header';
import { Footer } from './sukukUpdated/components/Footer';
import { FloatingActions } from './sukukUpdated/components/FloatingActions';
import { StickyConversionBar } from './sukukUpdated/components/StickyConversionBar';
import { PartnersMarquee } from './sukukUpdated/components/PartnersMarquee';
import { ProjectsGallery } from './sukukUpdated/components/ProjectsGallery';
import { StatsBar } from './sukukUpdated/components/StatsBar';
import { PHONE_NUMBER, PHONE_DISPLAY, WHATSAPP_NUMBER } from './sukukUpdated/data/siteData';
import './sukukUpdated.css';

const whatsapp = (message: string) => `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;

type LandingPage = {
  slug: string; service: string; title: string; description: string; heroCopy: string; primaryKeyword?: string;
  whatsapp: string; choices: string[]; services: string[][]; process: string[]; faqs: string[][];
  keywordGroups?: { primary?: string[]; supporting?: string[]; longtail?: string[] };
  cta?: string; formTitle?: string; servicesTitle?: string; servicesDescription?: string; whyTitle?: string;
};

function Hero({ page }: { page: LandingPage }) {
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [service, setService] = useState(page.choices[0] || page.service);
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!phone.trim()) return; window.open(whatsapp(`${page.whatsapp}\n\nالاسم: ${name || 'عميل كريم'}\nالجوال: ${phone}\nالخدمة: ${service}`), '_blank', 'noopener,noreferrer'); };
  return <section id="home" className="min-h-[92vh] flex flex-col justify-center pt-28 pb-16 relative overflow-hidden bg-[#2B0F16]">
    <div className="sukuk-hero-surface absolute inset-0 z-0" aria-hidden="true" />
    <div className="container mx-auto px-4 lg:max-w-7xl relative z-10"><div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
      <div className="lg:col-span-7 text-center lg:text-right">
        <div className="flex flex-wrap items-center justify-center lg:justify-start gap-2 mb-6"><div className="inline-flex items-center gap-2 bg-neutral-900/80 text-[#FEB922] px-3.5 py-1.5 rounded-full text-xs font-bold border border-amber-400/30 backdrop-blur-md shadow-lg"><CheckCircle2 className="w-3.5 h-3.5"/><span>مكتب استشارات هندسية ومساحية مرخص</span></div><div className="inline-flex items-center gap-1.5 bg-neutral-900/80 text-stone-200 px-3 py-1.5 rounded-full text-xs font-medium border border-white/15 backdrop-blur-md shadow-lg"><ShieldCheck className="w-3.5 h-3.5 text-emerald-400"/><span>اعتماد بلدي • حلول دقيقة • متابعة مهنية</span></div></div>
        <div className="inline-block bg-[#2B0F16]/70 border border-[#C9973C]/40 rounded-3xl px-5 py-5 sm:px-8 sm:py-7 backdrop-blur-md shadow-2xl"><span className="text-[#FEB922] font-bold text-sm sm:text-base">حلول هندسية معتمدة في المملكة</span><h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-[2.6rem] xl:text-[2.9rem] font-black text-white leading-[1.3] sm:leading-[1.25] tracking-tight drop-shadow-[0_2px_4px_rgba(0,0,0,0.95)] drop-shadow-[0_6px_20px_rgba(43,15,22,0.95)] mt-3">أفضل مكتب معتمد في المملكة<br/><span className="text-transparent bg-clip-text bg-gradient-to-l from-[#F2C230] via-[#FEB922] to-[#F7D97A] drop-shadow-[0_2px_10px_rgba(0,0,0,0.9)]">{page.service}</span></h1><p className="text-stone-200 text-base sm:text-lg leading-relaxed mt-5 max-w-2xl">{page.heroCopy}</p><div className="flex flex-wrap justify-center lg:justify-start gap-3 mt-6"><a href="#contact" className="bg-[#C9973C] hover:bg-[#B8860B] text-[#2B0F16] font-black px-6 py-3 rounded-xl transition-all shadow-lg">{page.cta || `اطلب خدمة ${page.service}`}</a><a href={whatsapp(page.whatsapp)} target="_blank" rel="noreferrer" className="bg-[#25D366] hover:bg-[#20bd5a] text-white font-bold px-6 py-3 rounded-xl flex items-center gap-2 shadow-lg"><MessageCircle className="w-5 h-5"/> تحدث مع مهندس</a></div></div>
      </div>
      <div className="lg:col-span-5"><div className="sukuk-glass-form bg-white/80 backdrop-blur-2xl rounded-3xl p-6 sm:p-7 shadow-[0_20px_60px_rgba(0,0,0,0.35)] border border-white/70 border-t-4 border-t-[#C9973C]"><div className="text-center mb-5"><div className="inline-flex items-center gap-1.5 bg-amber-50 text-[#9E7124] border border-[#C9973C]/30 px-3 py-1 rounded-full text-xs font-bold mb-2"><FileCheck2 className="w-3.5 h-3.5"/> استشارة مجانية • تسعيرة فورية</div><h3 className="text-xl sm:text-2xl font-black text-[#2B0F16]">{page.formTitle || `طلب خدمة ${page.service}`}</h3><p className="text-xs text-stone-500 mt-1">حدد احتياجك وسيتم التواصل معك مباشرة عبر الواتساب</p></div><form onSubmit={submit} className="space-y-4 text-right"><div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5"><input required value={name} onChange={e=>setName(e.target.value)} className="w-full px-3 py-3 bg-white/90 border border-[#2B0F16]/15 rounded-xl text-[#2B0F16] text-sm" placeholder="الاسم الكريم"/><input required value={phone} onChange={e=>setPhone(e.target.value)} dir="ltr" className="w-full px-3 py-3 bg-white/90 border border-[#2B0F16]/15 rounded-xl text-[#2B0F16] text-sm text-right" placeholder="05x xxx xxxx"/></div><select value={service} onChange={e=>setService(e.target.value)} className="w-full px-3 py-3 bg-white/90 border border-[#2B0F16]/15 rounded-xl text-[#2B0F16] text-sm">{page.choices.map(x=><option key={x}>{x}</option>)}</select><button type="submit" className="w-full bg-[#25D366] hover:bg-[#20bd5a] text-white font-black py-3.5 rounded-xl flex items-center justify-center gap-2 shadow-lg"><Send className="w-4 h-4"/> إرسال الطلب عبر الواتساب</button><div className="flex items-center justify-between text-[11px] text-stone-500"><span className="flex items-center gap-1 text-emerald-700 font-bold"><ShieldCheck className="w-3.5 h-3.5"/> بياناتك سرية ومحمية</span><span>رد فوري خلال دقائق</span></div></form></div></div>
    </div></div>
  </section>;
}

function Services({ page }: { page: LandingPage }) { return <section id="services" className="py-20 sm:py-24 bg-gradient-to-b from-[#F7F4EE]/50 via-white to-[#F7F4EE]/30 relative"><div className="container mx-auto px-4 lg:max-w-7xl relative z-10"><div className="text-center max-w-3xl mx-auto mb-16"><div className="inline-flex items-center gap-2 bg-amber-50 border border-rkGold/30 text-rkGoldDark text-xs font-bold px-3.5 py-1.5 rounded-full mb-3"><ShieldCheck className="w-4 h-4"/> خدمات متخصصة بمخرجات واضحة</div><h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-[#2B0F16] mb-4">{page.servicesTitle || `خدماتنا المتخصصة في ${page.service}`}</h2><p className="text-stone-600 text-sm sm:text-base md:text-lg leading-relaxed">{page.servicesDescription || `حلول دقيقة ومتكاملة في ${page.service}، تبدأ بفهم احتياجك وتنتهي بمخرج هندسي واضح قابل للمراجعة.`}</p></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">{page.services.map(([title,desc],i)=><div key={title} className="bg-white rounded-2xl border border-stone-200 shadow-sm hover:shadow-xl hover:-translate-y-1.5 transition-all relative flex flex-col overflow-hidden"><div className="p-6 flex flex-col flex-grow"><div className="flex items-center justify-between mb-5"><span className="text-xs font-black text-rkGold bg-amber-50 px-2 py-0.5 rounded-md">{String(i+1).padStart(2,'0')}</span><span className="text-[11px] font-bold text-[#5C1F2E] bg-[#5C1F2E]/5 px-2.5 py-0.5 rounded-full">{i===0?'الأكثر طلباً':i===1?'خدمة متخصصة':'مخرج واضح'}</span></div><div className="flex items-center gap-4 mb-4"><div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-amber-50 to-[#F7F4EE] border border-[#C9973C]/40 text-[#C9973C] flex items-center justify-center shrink-0"><FileCheck2 className="w-7 h-7"/></div><h3 className="font-extrabold text-[#2B0F16] text-base md:text-lg leading-snug">{title}</h3></div><div className="w-10 h-0.5 bg-gradient-to-r from-rkGold to-transparent mb-3.5"/><p className="text-xs sm:text-sm text-stone-600 leading-relaxed">{desc}</p><div className="mt-auto pt-4 border-t border-stone-100 space-y-2"><div className="flex items-center gap-2 text-xs text-stone-700"><CheckCircle2 className="w-3.5 h-3.5 text-[#C9973C]"/> مراجعة المتطلبات والبيانات</div><div className="flex items-center gap-2 text-xs text-stone-700"><CheckCircle2 className="w-3.5 h-3.5 text-[#C9973C]"/> مخرج هندسي قابل للمراجعة</div></div></div><div className="p-4 bg-stone-50/70 border-t border-stone-100"><a href={whatsapp(`${page.whatsapp}\nالخدمة المطلوبة: ${title}`)} target="_blank" rel="noreferrer" className="w-full bg-[#5C1F2E] text-white text-xs font-bold py-2.5 rounded-xl flex items-center justify-center gap-1.5"><MessageCircle className="w-3.5 h-3.5 text-[#FEB922]"/> طلب الخدمة <ArrowUpRight className="w-3.5 h-3.5"/></a></div></div>)}</div></div></section>; }

function Why({ page }: { page: LandingPage }) { const reasons=['خبرة مرتبطة بالخدمة','متطلبات ومخرجات واضحة','متابعة مهنية حتى التسليم']; return <section className="py-20 sm:py-24 bg-[#F7F4EE] border-t border-stone-200/60"><div className="container mx-auto px-4 lg:max-w-7xl"><div className="text-center max-w-3xl mx-auto mb-14"><span className="inline-flex bg-amber-50 border border-rkGold/30 text-rkGoldDark text-xs font-bold px-3.5 py-1.5 rounded-full mb-3">دقة • وضوح • التزام</span><h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-[#2B0F16]">{page.whyTitle || `لماذا تختار مكتب ريان في ${page.service}؟`}</h2><p className="text-stone-600 mt-4">نربط الخبرة الهندسية بمتطلبات {page.service} لنقدم لك قراراً أوضح وتواصلاً منظماً من أول خطوة حتى التسليم.</p></div><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{reasons.map((title,i)=><div key={title} className="bg-white rounded-2xl p-7 border border-stone-200 shadow-sm text-center"><div className="w-14 h-14 mx-auto rounded-2xl bg-[#5C1F2E] text-[#C9973C] flex items-center justify-center mb-4"><ShieldCheck className="w-7 h-7"/></div><h3 className="font-extrabold text-[#2B0F16] text-lg mb-2">{title}</h3><p className="text-sm text-stone-600 leading-relaxed">{i===0? page.description : i===1?'نوضح المطلوب والوثائق ونطاق العمل قبل البدء.':'نشرح لك المرحلة التالية ونبقي المتابعة سهلة ومباشرة.'}</p></div>)}</div></div></section>; }

function Process({ page }: { page: LandingPage }) { return <section className="py-20 sm:py-24 bg-white border-t border-stone-200/60"><div className="container mx-auto px-4 lg:max-w-7xl"><div className="text-center max-w-3xl mx-auto mb-14"><span className="inline-flex bg-amber-50 border border-rkGold/30 text-rkGoldDark text-xs font-bold px-3.5 py-1.5 rounded-full mb-3">خطوات العمل المعتمدة</span><h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-[#2B0F16]">آلية وإجراءات العمل</h2><p className="text-stone-600 mt-4">منهجية واضحة ومبسطة لضمان راحة العميل وسرعة الإنجاز في {page.service}.</p></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-6">{page.process.map((item,i)=><div key={item} className="bg-[#F7F4EE] rounded-2xl p-8 text-center border border-stone-200 relative shadow-sm"><div className="w-14 h-14 mx-auto rounded-full bg-[#5C1F2E] text-rkGold font-black text-2xl flex items-center justify-center mb-4 ring-4 ring-amber-50">{String(i+1).padStart(2,'0')}</div><h4 className="font-extrabold text-[#2B0F16] text-lg">{item}</h4></div>)}</div></div></section>; }

function FAQ({ page }: { page: LandingPage }) { const [open,setOpen]=useState(0); return <section id="faq" className="py-20 sm:py-24 bg-white border-t border-stone-200/60"><div className="container mx-auto px-4 lg:max-w-3xl"><div className="text-center mb-14"><span className="inline-flex bg-amber-50 border border-rkGold/30 text-rkGoldDark text-xs font-bold px-3.5 py-1.5 rounded-full mb-3">إجابات واضحة ومباشرة</span><h2 className="text-3xl sm:text-4xl font-extrabold text-[#2B0F16]">الأسئلة الأكثر شيوعاً حول {page.service}</h2></div><div className="space-y-4">{page.faqs.map(([q,a],i)=><div key={q} className="bg-stone-50 border border-stone-200 rounded-2xl overflow-hidden"><button onClick={()=>setOpen(open===i?-1:i)} className="w-full p-5 font-bold text-[#2B0F16] text-right flex justify-between items-center gap-4"><span>{q}</span>{open===i?<Minus className="w-5 h-5 text-rkGold"/>:<Plus className="w-5 h-5 text-stone-500"/>}</button>{open===i&&<div className="px-5 pb-5 text-sm text-stone-600 leading-relaxed border-t border-stone-100 pt-4">{a}</div>}</div>)}</div></div></section>; }

function Contact({ page }: { page: LandingPage }) { const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [details,setDetails]=useState(''); const submit=(e:React.FormEvent)=>{e.preventDefault(); if(!phone.trim())return; window.open(whatsapp(`${page.whatsapp}\nالاسم: ${name}\nالجوال: ${phone}\nالتفاصيل: ${details}`),'_blank','noopener,noreferrer')}; return <section id="contact" className="py-20 bg-[#F4EBDD] text-[#2B0F16] border-t border-rkGold/30"><div className="container mx-auto px-4 lg:max-w-6xl"><div className="text-center mb-14"><h2 className="text-4xl md:text-5xl font-black text-[#2B0F16] mb-4">تواصل معنا الآن</h2><p className="text-[#5C1F2E] text-base sm:text-lg">أرسل تفاصيل احتياجك في {page.service} وسيتواصل معك المهندس المختص.</p></div><div className="grid grid-cols-1 lg:grid-cols-12 gap-8"><div className="lg:col-span-7 sukuk-glass-form rounded-3xl p-6 sm:p-8 text-right"><h3 className="text-2xl font-bold text-[#5C1F2E] mb-6">طلب خدمة أو استفسار</h3><form onSubmit={submit} className="space-y-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><input required value={name} onChange={e=>setName(e.target.value)} className="w-full px-4 py-3 bg-white/90 text-[#2B0F16] border border-white/40 rounded-xl" placeholder="الاسم الكامل"/><input required value={phone} onChange={e=>setPhone(e.target.value)} dir="ltr" className="w-full px-4 py-3 bg-white/90 text-[#2B0F16] border border-white/40 rounded-xl text-right" placeholder="رقم الجوال"/></div><textarea rows={4} value={details} onChange={e=>setDetails(e.target.value)} className="w-full px-4 py-3 bg-white/90 text-[#2B0F16] border border-white/40 rounded-xl resize-none" placeholder={`اكتب تفاصيل احتياجك في ${page.service}...`}/><button type="submit" className="w-full bg-[#25D366] text-white font-bold py-3.5 rounded-xl flex items-center justify-center gap-2"><MessageCircle className="w-5 h-5"/> إرسال الطلب عبر الواتساب</button></form></div><div className="lg:col-span-5 flex flex-col gap-5"><a href={`tel:${PHONE_NUMBER}`} className="bg-[#2B0F16] p-6 rounded-3xl border border-rkGold/30 flex items-center justify-between shadow-xl"><div className="w-14 h-14 bg-rkGold text-[#2B0F16] rounded-2xl flex items-center justify-center"><Phone className="w-6 h-6"/></div><div><div className="text-gray-300 text-sm">اتصال هاتفي مباشر</div><div className="text-xl font-black text-white" dir="ltr">{PHONE_DISPLAY}</div></div></a><div className="bg-[#2B0F16] p-6 rounded-3xl border border-rkGold/30 flex-grow"><div className="text-rkGold font-bold mb-3">نطاق الخدمة</div><p className="text-gray-200 text-sm leading-relaxed">نراجع تفاصيل طلبك ونوضح المتطلبات والمخرج المناسب قبل بدء التنفيذ.</p></div></div></div></div></section>; }

export default function ServiceLandingPage({ page }: { page: LandingPage }) { useEffect(()=>{document.title=page.title; let d=document.querySelector('meta[name="description"]') as HTMLMetaElement|null; if(!d){d=document.createElement('meta');d.name='description';document.head.appendChild(d)} d.content=page.description; let c=document.querySelector('link[rel="canonical"]') as HTMLLinkElement|null; if(!c){c=document.createElement('link');document.head.appendChild(c)} c.rel='canonical'; c.href=`${window.location.origin}${import.meta.env.BASE_URL}lp/${page.slug}/`;},[page]); return <div dir="rtl" className="sukuk-updated-page min-h-screen bg-[#F7F4EE] text-[#2F2F2F] pb-16 lg:pb-0"><Header/><main><Hero page={page}/><Services page={page}/><Why page={page}/><Process page={page}/><PartnersMarquee/><ProjectsGallery/><StatsBar/><FAQ page={page}/><Contact page={page}/></main><Footer/><FloatingActions/><StickyConversionBar/></div>; }
